name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: fstevens30/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.bbbb7801-0695-4f89-9bdb-663d620f1e79 }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
